# Generated by Django 3.0.1 on 2020-01-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productiv', '0002_productivity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivity',
            name='name',
        ),
        migrations.AddField(
            model_name='productivity',
            name='date',
            field=models.CharField(default='date.today()', max_length=120),
        ),
    ]
